### ISSUE TITLE
Multiline input

### ISSUE THREAD

**Issue by inakrin** [screepers/screeps-multimeter#13]
Is there a way to use multyline input? Cannot paste long chunks of code like I do with original console.

**Comment by CGamesPlay** [comment]
Hello, thanks for submitting an issue! There is currently not a way to handle this. The problem is that there's no way to differentiate between pasting a newline, or pressing enter: they appear the same to multimeter.

There are a few techniques that can be used to add support for this, but they depend on the terminal program you're using.

- [Bracketed paste mode](https://cirw.in/blog/bracketed-paste) would be the ideal solution, since it's very reliable for terminals that support it.
- Escaping the newlines, or doing bracket matching, like the solutions described [in this StackOverflow answer](https://stackoverflow.com/questions/6713056/how-do-i-paste-multi-line-bash-codes-into-terminal-and-run-it-all-at-once).

I would be willing to talk about any of these solutions if you have interest in adding support!
