### ISSUE TITLE
UTF-8 Encoding

### ISSUE THREAD

**Issue by FormatToday** [screepers/screeps-multimeter#18]
The console only supports English now

**Comment by pyrodogg** [comment]
Multimeter currently supports more than English characters, but not the full Unicode set. This is due to how Blessed is currently configured. By setting `fullUnicode: true` the full range of double width unicode characters is possible.

[Screen options](https://www.npmjs.com/package/blessed#screen-from-node)
> fullUnicode - Allow for rendering of East Asian double-width characters, utf-16 surrogate pairs, and unicode combining characters. This allows you to display text above the basic multilingual plane. This is behind an option because it may affect performance slightly negatively. Without this option enabled, all double-width, surrogate pair, and combining characters will be replaced by '??', '?', '' respectively. (NOTE: iTerm2 cannot display combining characters properly. Blessed simply removes them from an element's content if iTerm2 is detected).

**Comment by FormatToday** [comment]
OK,Thank you
