### ISSUE TITLE
How to use with authentication tokens?

### ISSUE THREAD

**Issue by SystemParadox** [screepers/screeps-multimeter#7]
Since Feb 2018 username/password authentication does not work - you have to use authentication tokens. Does screeps-multimeter support this?

Thanks.

**Comment by CGamesPlay** [comment]
Hey, unfortunately I haven't been active in Screeps in a few months. However, the underlying API is provided by https://github.com/screepers/node-screeps-api and version 2.0 supports the new auth mechanism. I'd be happy to accept a pull request if you were to move the library over to it!

**Comment by SystemParadox** [comment]
Ok, I started having a look at this. Would you be able to explain why you needed to subclass ScreepsAPI?

**Comment by CGamesPlay** [comment]
Yeah. In the version 1 API there was a bug, which I fixed by subclassing:

- The socket connection never sent pings, so if your laptop went to sleep you might be disconnected and never realize it.
- The API didn't provide an unsubscribe method for socket events.
- When you reconnected to with an existing API instance, you have to resubscribe to events, but the local instance never removed local listeners, so each event would fire twice.

I think all of these have since been fixed in the v2 API.

**Comment by CGamesPlay** [comment]
Just pushed v1.5.0 which closes this. Sorry for the delay and thanks again for contributing!

**Comment by SystemParadox** [comment]
Thanks!
